import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import PomodoroTimerListProvider from "./providers/PomodoroTimerListProvider";
import TimerProvider from "./providers/TimerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo + Pomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PomodoroTimerListProvider>
          <TimerProvider>
            <Header></Header>
            {children}
          </TimerProvider>
        </PomodoroTimerListProvider>
      </body>
    </html>
  );
}
